### ISSUE TITLE
README has wrong info for downloads directory

### ISSUE THREAD

**Issue by bmonty** [dperson/transmission#33]
The README file has the wrong path for the download directory.  README shows the path as `/var/lib/torrent-daemon/downloads` and the container actually creates `/var/lib/torrent-daemon/Downloads`.

**Comment by dperson** [comment]
I'm not seeing that, I spun up a fresh container image and it shows the same path that's in the `README.md`...

```
$ sudo docker run -it --rm dperson/transmission cat /var/lib/transmission-daemon/info/settings.json                            
{
    "blocklist-enabled": 0, 
    "dht-enabled": true,
    "download-dir": "/var/lib/transmission-daemon/downloads",
    "incomplete-dir": "/var/lib/transmission-daemon/incomplete",
    "incomplete-dir-enabled": true,
    "download-limit": 100, 
    "download-limit-enabled": 0, 
    "encryption": 1, 
    "max-peers-global": 200, 
    "peer-port": 51413, 
    "peer-socket-tos": "lowcost",
    "pex-enabled": 1, 
    "port-forwarding-enabled": 0, 
    "queue-stalled-enabled": true,
    "ratio-limit-enabled": true,
    "rpc-authentication-required": 1, 
    "rpc-password": "transmission", 
    "rpc-port": 9091, 
    "rpc-username": "transmission", 
    "rpc-whitelist": "127.0.0.1", 
    "upload-limit": 100, 
    "upload-limit-enabled": 0
}
```

**Comment by bmonty** [comment]
I tried the same command you used and I got the same result.  However, I get a much different settings file than the one you posted when I start the container in my config.

```
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": true,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/var/lib/transmission-daemon/Downloads",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": true,
    "incomplete-dir": "/var/lib/transmission-daemon/Downloads",
    "incomplete-dir-enabled": false,
    "lpd-enabled": false,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": false,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": true,
    "rename-partial-files": true,
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-password": "****",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "****",
    "rpc-whitelist": "*",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 18,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true
}
```

I'm creating the container using docker-compose.  Here is the config file:

```
version: '3'

services:
    transmission:
        image: dperson/transmission
        restart: always
        ports:
            - "127.0.0.1:50008:9091"
            - "51413:51413"
            - "51413:51413/udp"
        volumes:
            - ./downloads:/var/lib/transmission-daemon/Downloads
            - ./info:/var/lib/transmission-daemon/info
            - ./incomplete:/var/log/transmission-daemon/incomplete
        environment:
            - TRUSER=****
            - TRPASSWD=****
            - TZ=CST6CDT
            - USERID=110
            - GROUPID=1002
            - TR_IDLE_SEEDING_LIMIT_ENABLED=true
            - TR_RATIO_LIMIT_ENABLED=true
```

I tried removing all the files at `./info` and recreating the container.  The `download-dir` value in the created `settings.json` was `/var/lib/transmission-daemon/Downloads`.
